# Generated by Django 4.2.6 on 2023-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletag_tag_articletag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='main',
            new_name='is_main',
        ),
    ]
