# Generated by Django 4.2.6 on 2023-10-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_main_articletag_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='articles_tag', through='articles.Scope', to='articles.article'),
        ),
    ]
